fix: build errors
- implement a minimal radiotap header for fix the error:
    incomplete definition of type 'struct IEEE80211_RADIOTAP_HEADER'

- fix 'CFG_FIX_2_TX_PORT' is not defined due to -Werror,-Wundef

- fix error: use of undeclared identifier '__ulFlags'
    use KAL_SPIN_LOCK_DECLARATION macro defined in os/linux/include

Change-Id: I0f14c580ff25e3f4db00417ea17f581c1d770508
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>