fix: error: use of undeclared identifier 'i'
error introduced in commit b2cc779

Change-Id: I5a305ef831411b32cbdf0b8a6f9f2c8046bb9a6e
Signed-off-by: nullptr_t <nullptr.oss@gmail.com>